networks:
  default:
  traefik_default:
    external: true

volumes:
  db:

services:

  app:
    image: fpix/cd-diary
    networks:
     - traefik_default
     - default
    depends_on:
      - db
    environment:
      - PROJECT_NAME=climbing-api
      - PROJECT_DESCRIPTION=API to manage spot, route and pitch data for the climbing diary app.
      - PROJECT_VERSION=alpha
      - SERVER_IP=0.0.0.0
      - SERVER_PORT=8000
      - BACKEND_CORS_ORIGINS=["https://climbing-api.florianpix.de"]
      - DATABASE_URI=mongodb://cd-diary:9SfKhCKyedig2tfiWqoRSbB4@db/?retryWrites=true&w=majority
      - AUTH0_DOMAIN=climbing-diary.eu.auth0.com
      - AUTH0_API_AUDIENCE=climbing-diary-API
    labels:
      - traefik.enable=true
      - traefik.http.routers.climbing-api.rule=Host(`climbing-api.florianpix.de`)
      - traefik.http.routers.climbing-api.entrypoints=websecure
      - traefik.http.routers.climbing-api.tls.certresolver=myresolver
      - traefik.http.services.climbing-api.loadbalancer.server.port=8000

  db:
    image: mongo:4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: cd-diary
      MONGO_INITDB_ROOT_PASSWORD: 9SfKhCKyedig2tfiWqoRSbB4
    volumes:
      - db:/data/db
