volumes:
  db_test:

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: cd-diary
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - db_test:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: cd-diary
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://cd-diary:password@mongo:27017/

# For local development, database only.
