name: testing

on: [pull_request]

jobs:
  testingClimbingAPI:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Test
        run: |
          cd ./src/climbingAPI
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/cd-diary:latest .
          docker-compose up -d
          docker exec climbingapi-app-1 pip install pytest
          docker exec climbingapi-app-1 pip install pytest-cov
          docker exec climbingapi-app-1 coverage run -m pytest .
          docker exec climbingapi-app-1 coverage report
          docker-compose down

  testingMediaAPI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Test
        run: |
          cd ./src/mediaAPI
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/cd-media:latest .
          docker-compose up -d
          docker exec mediaapi-app-1 pip install pytest
          docker exec mediaapi-app-1 pip install pytest-cov
          docker exec mediaapi-app-1 coverage run -m pytest .
          docker exec mediaapi-app-1 coverage report
          docker-compose down