name: testing

on: [pull_request]

jobs:
  climbingAPI:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and compose
        run: |
          ls
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/cd-diary:latest .
          docker-compose up
          docker container list
  testClimbingAPI:
    runs-on: ubuntu-latest
    container: climbingapi-app-1
    steps:
      -
        name: Test
        run: |
          ls

