name: testing

on: [pull_request]

jobs:
  testing_climbingAPI:
    env:
      PROJECT_NAME: climbing-api
      PROJECT_DESCRIPTION: "API to manage spot, route and pitch data for the climbing diary app."
      PROJECT_VERSION: alpha
      SERVER_IP: 0.0.0.0
      SERVER_PORT: 8000
      BACKEND_CORS_ORIGINS: '["http://localhost:4200", "http://localhost:4200/", "http://localhost", "http://localhost:8000"]'
      DATABASE_URI: ${{ secrets.DATABASE_URI }}
      AUTH0_DOMAIN: climbing-diary.eu.auth0.com
      AUTH0_API_AUDIENCE: climbing-diary-API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/climbingAPI/requirements.txt
      - name: install pytest
        run: |
          pip install pytest
          pip install pytest-cov
      - name: test with pytest
        run: pytest src/climbingAPI/test_main.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
  testing_mediaAPI:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: mediaAPI
      SERVER_IP: 0.0.0.0
      SERVER_PORT: 8001
      BACKEND_CORS_ORIGINS: '[ "http://localhost:4200", "http://localhost:4200/", "http://localhost", "http://localhost:8000" ]'
      POSTGRES_SERVER: db
      POSTGRES_USER: cd-media
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: cd-media
      AUTH0_DOMAIN: climbing-diary.eu.auth0.com
      AUTH0_API_AUDIENCE: climbing-diary-API
      S3_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT_URL }}
      S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      S3_BUCKET_NAME: testing-cd-media
      S3_SIGNATURE_VERSION: s3v4
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/mediaAPI/requirements.txt
      - name: install pytest
        run: |
          pip install pytest
          pip install pytest-cov
      - name: test with pytest
        run: pytest src/mediaAPI/test_main.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html